// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQhpI3sNXYLUfRntGAxD0I6ykh576FAnM',
    appId: '1:433496120553:web:baee89ff9cbb656bcda478',
    messagingSenderId: '433496120553',
    projectId: 'cutis-ai',
    authDomain: 'cutis-ai.firebaseapp.com',
    storageBucket: 'cutis-ai.appspot.com',
    measurementId: 'G-KCCJXKRTBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA92zSfks4NgED04JwN2IuqOh1FyuAIFYs',
    appId: '1:433496120553:android:c5b25515b21c7b55cda478',
    messagingSenderId: '433496120553',
    projectId: 'cutis-ai',
    storageBucket: 'cutis-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCab_bFS9YXD3Ax3MAGDN4irZYWEewjQHI',
    appId: '1:433496120553:ios:e9eb10b4ecc182aacda478',
    messagingSenderId: '433496120553',
    projectId: 'cutis-ai',
    storageBucket: 'cutis-ai.appspot.com',
    iosBundleId: 'com.example.cutisAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCab_bFS9YXD3Ax3MAGDN4irZYWEewjQHI',
    appId: '1:433496120553:ios:e9eb10b4ecc182aacda478',
    messagingSenderId: '433496120553',
    projectId: 'cutis-ai',
    storageBucket: 'cutis-ai.appspot.com',
    iosBundleId: 'com.example.cutisAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQhpI3sNXYLUfRntGAxD0I6ykh576FAnM',
    appId: '1:433496120553:web:dbc2d8a65ff87acfcda478',
    messagingSenderId: '433496120553',
    projectId: 'cutis-ai',
    authDomain: 'cutis-ai.firebaseapp.com',
    storageBucket: 'cutis-ai.appspot.com',
    measurementId: 'G-P5MGB4R4Q2',
  );
}
